"""update misses with requires

Revision ID: 19d4d950784
Revises: 3cd5ab34d0
Create Date: 2014-09-16 11:43:44.499057

"""

# revision identifiers, used by Alembic.
revision = '19d4d950784'
down_revision = '3cd5ab34d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('misses', 'message',
               existing_type=sa.BIGINT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('misses', 'message',
               existing_type=sa.BIGINT(),
               nullable=True)
    ### end Alembic commands ###
