"""add datalog

Revision ID: 1cab6de23e5
Revises: 269915fe13c
Create Date: 2014-05-20 21:26:57.552567

"""

# revision identifiers, used by Alembic.
revision = '1cab6de23e5'
down_revision = '269915fe13c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datalogs_description'), 'datalogs', ['description'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datalogs_description'), table_name='datalogs')
    op.drop_table('datalogs')
    ### end Alembic commands ###
