"""add sfv data

Revision ID: 25450d45211
Revises: 35c1d30bca4
Create Date: 2014-09-08 17:33:08.572415

"""

# revision identifiers, used by Alembic.
revision = '25450d45211'
down_revision = '35c1d30bca4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sfvs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data', sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.add_column('releases', sa.Column('sfv_id', sa.Integer(), nullable=True))
    op.add_column('releases', sa.Column('sfv_metablack_id', sa.Integer(), nullable=True))

    op.create_index(op.f('ix_releases_sfv_id'), 'releases', ['sfv_id'], unique=False)
    op.create_index(op.f('ix_releases_sfv_metablack_id'), 'releases', ['sfv_metablack_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_sfv_metablack_id'), table_name='releases')
    op.drop_index(op.f('ix_releases_sfv_id'), table_name='releases')
    op.drop_column('releases', 'sfv_metablack_id')
    op.drop_column('releases', 'sfv_id')
    op.drop_table('sfvs')
    ### end Alembic commands ###
