"""add hash to binary

Revision ID: 269915fe13c
Revises: 29d092d30bc
Create Date: 2014-05-20 15:47:04.704985

"""

# revision identifiers, used by Alembic.
revision = '269915fe13c'
down_revision = '29d092d30bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binaries', sa.Column('hash', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_binaries_hash'), 'binaries', ['hash'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binaries_hash'), table_name='binaries')
    op.drop_column('binaries', 'hash')
    ### end Alembic commands ###
