"""added cascade to files and moved the relationship

Revision ID: 29d092d30bc
Revises: 75fe822c05
Create Date: 2014-05-17 11:46:04.388079

"""

# revision identifiers, used by Alembic.
revision = '29d092d30bc'
down_revision = '75fe822c05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_release_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_release_id_fkey'), 'files', 'releases', ['release_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_release_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_release_id_fkey'), 'files', 'releases', ['release_id'], ['id'])
    ### end Alembic commands ###
