"""add field blacklists

Revision ID: 31198df37a9
Revises: 1cab6de23e5
Create Date: 2014-08-02 19:36:06.391237

"""

# revision identifiers, used by Alembic.
revision = '31198df37a9'
down_revision = '1cab6de23e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklists', sa.Column('field', sa.String(), nullable=False, server_default='subject'))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklists', 'field')
    ### end Alembic commands ###
