"""discrete size field

Revision ID: 35c1d30bca4
Revises: 31198df37a9
Create Date: 2014-08-03 20:30:45.992859

"""

# revision identifiers, used by Alembic.
revision = '35c1d30bca4'
down_revision = '31198df37a9'

from alembic import op
import sqlalchemy as sa

from pynab.db import Release, File


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('size', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###

    stmt = sa.select([sa.func.sum(File.size)]).where(Release.id == File.release_id).limit(1)
    op.execute(Release.__table__.update().values(size=stmt))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'size')
    ### end Alembic commands ###
