"""add clean name and category to binary for plpython creation

Revision ID: 370728c2b63
Revises: 1cbc2db68e8
Create Date: 2015-01-07 16:47:52.544408

"""

# revision identifiers, used by Alembic.
revision = '370728c2b63'
down_revision = '1cbc2db68e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binaries', sa.Column('category', sa.String(), nullable=True))
    op.add_column('binaries', sa.Column('clean_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('binaries', 'clean_name')
    op.drop_column('binaries', 'category')
    ### end Alembic commands ###
