"""add unique name column to pre

Revision ID: 3821d174074
Revises: 4c7beb6960
Create Date: 2015-01-10 20:54:45.426410

"""

# revision identifiers, used by Alembic.
revision = '3821d174074'
down_revision = '4c7beb6960'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pres_name_key', 'pres', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pres_name_key', 'pres', type_='unique')
    ### end Alembic commands ###
