"""Initial setup.

Revision ID: 38ad29f9766
Revises: None
Create Date: 2014-05-07 19:44:58.833194

"""

# revision identifiers, used by Alembic.
revision = '38ad29f9766'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
