"""add indexes to pres
Revision ID: 39a3cc0bb0d
Revises: 3379cecd3a7
Create Date: 2015-01-30 15:17:53.649299
"""

# revision identifiers, used by Alembic.

revision = '39a3cc0bb0d'
down_revision = '3379cecd3a7'

from alembic import op


def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pres_requestgroup'), 'pres', ['requestgroup'], unique=False)
    op.create_index(op.f('ix_pres_requestid'), 'pres', ['requestid'], unique=False)
    ### end Alembic commands ###

def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pres_requestid'), table_name='pres')
    op.drop_index(op.f('ix_pres_requestgroup'), table_name='pres')
    ### end Alembic commands ###

