"""change release unique key from name-posted to name-group-posted

Revision ID: 3ee16503d82
Revises: 39a3cc0bb0d
Create Date: 2015-02-13 14:53:15.432464

"""

# revision identifiers, used by Alembic.

revision = '3ee16503d82'
down_revision = '39a3cc0bb0d'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('releases_name_posted_key', 'releases')
    op.create_unique_constraint('releases_name_group_id_posted_key', 'releases', ['name', 'group_id', 'posted'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('releases_name_posted_key', 'releases', ['name', 'posted'])
    op.drop_constraint('releases_name_group_id_posted_key', 'releases')
    ### end Alembic commands ###

