"""add pre model

Revision ID: 4c7beb6960
Revises: 1cbc2db68e8
Create Date: 2015-01-08 10:51:58.996647

"""

# revision identifiers, used by Alembic.
revision = '4c7beb6960'
down_revision = 'c5c72142b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pres',
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('searchname', sa.String(), nullable=True),
    )
    op.create_index(op.f('ix_pre_name'), 'pres', ['name'], unique=False)
    op.drop_constraint('pre_name_key', 'pres', type_='unique')
    op.drop_index('pre_title', table_name='pres')
    op.create_index(op.f('ix_releases_pre_id'), 'releases', ['pre_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pres')
    ### end Alembic commands ###
