"""add pre model

Revision ID: 4c7beb6960
Revises: 1cbc2db68e8
Create Date: 2015-01-08 10:51:58.996647

"""

# revision identifiers, used by Alembic.
revision = '4c7beb6960'
down_revision = 'c5c72142b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pre', 'searchname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_pre_name'), 'pre', ['name'], unique=False)
    op.drop_constraint('pre_name_key', 'pre', type_='unique')
    op.drop_index('pre_title', table_name='pre')
    op.create_index(op.f('ix_releases_pre_id'), 'releases', ['pre_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releases_pre_id'), table_name='releases')
    op.create_index('pre_title', 'pre', ['name'], unique=False)
    op.create_unique_constraint('pre_name_key', 'pre', ['name'])
    op.drop_index(op.f('ix_pre_name'), table_name='pre')
    op.alter_column('pre', 'searchname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pre', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
