"""added cascade to files and moved the relationship

Revision ID: 560b6774dc9
Revises: 75fe822c05
Create Date: 2014-05-17 11:13:39.198964

"""

# revision identifiers, used by Alembic.
revision = '560b6774dc9'
down_revision = '75fe822c05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
