"""add set null on regex deletion

Revision ID: 57d67e16149
Revises: 18ced36d0df
Create Date: 2015-11-01 21:34:49.416257

"""

# revision identifiers, used by Alembic.
revision = '57d67e16149'
down_revision = '18ced36d0df'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('releases_regex_id_fkey'), 'releases', type_='foreignkey')
    op.create_foreign_key(op.f('releases_regex_id_fkey'), 'releases', 'regexes', ['regex_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('releases_regex_id_fkey'), 'releases', type_='foreignkey')
    op.create_foreign_key(op.f('releases_regex_id_fkey'), 'releases', 'regexes', ['regex_id'], ['id'])
    ### end Alembic commands ###
