"""Add index to TvShow

Revision ID: 75fe822c05
Revises: 53928162b90
Create Date: 2014-05-11 10:27:16.357262

"""

# revision identifiers, used by Alembic.
revision = '75fe822c05'
down_revision = '53928162b90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    op.create_index(op.f('ix_tvshows_name'), 'tvshows', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tvshows_name'), table_name='tvshows')
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    ### end Alembic commands ###
