"""add original name to releases

Revision ID: a06db5300d
Revises: 41996f6d756
Create Date: 2015-04-11 11:36:52.947150

"""

# revision identifiers, used by Alembic.
revision = 'a06db5300d'
down_revision = '41996f6d756'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('original_name', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'original_name')
    ### end Alembic commands ###
