"""add movies pk

Revision ID: b82b375466
Revises: 3bc50ecd0bb
Create Date: 2015-11-27 10:37:34.520196

"""

# revision identifiers, used by Alembic.
revision = 'b82b375466'
down_revision = '3bc50ecd0bb'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.schema


def dialect_supports_sequences():
    return op._proxy.migration_context.dialect.supports_sequences


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    engine = op.get_bind().engine
    inspector = sa.inspect(engine)

    if dialect_supports_sequences():
        col_data = inspector.get_columns('movies')
        for col in col_data:
            if col['name'] == 'id':
                if col['default'] is None:
                    try:
                        op.execute(sqlalchemy.schema.DropSequence(sqlalchemy.schema.Sequence('movies_id_seq')))
                    except:
                        op.execute('ROLLBACK')
                    op.execute(sqlalchemy.schema.CreateSequence(sqlalchemy.schema.Sequence('movies_id_seq')))
                    op.alter_column('movies', 'id', nullable=False, server_default=sa.text("nextval('movies_id_seq'::regclass)"))

        op.get_bind().execute("select setval('movies_id_seq', (select max(id) from movies));")
    ### end Alembic commands ###


def downgrade():
    pass

